# Generated by Django 3.2.9 on 2021-11-24 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='anwer_text',
            new_name='answer_text',
        ),
    ]
